## Objective

The aim of this notebook is to render the nodes and routes, and analyze them for further steps like merging or deleting nodes/routes

### Pre-requisites

In [4]:
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '../../')))

from utils.imports import *

### Load Saved Graph

In [5]:
# L_space_path= DATA_DIR / "pkl/belgium.pkl" # Path where the L-space graph was stored (original)
# L_space_path= DATA_DIR / "pkl/belgium_nodesCleaned.pkl" # Path where the clean L-space graph was stored (cleaned nodes)
L_space_path= DATA_DIR / "pkl/belgium_routesCleaned.pkl"  # Path where the clean L-space graph was stored (cleaned routes)
# L_space_path= DATA_DIR / "pkl/ireland_cleaned.pkl"  # Path where the clean L-space graph was stored (cleaned routes)

In [6]:
g = load_gtfs(str(PATH_TO_SQLITE))
L_graph=load_graph(L_space_path)
plot_graph(L_graph, back_map="OSM")

BokehDeprecationWarning: 'get_provider' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.

## Check Routes

- InterCity (IC): IC trains connect Belgium’s large cities. These trains only stop at the biggest train stations and sometimes cross international borders.
- Peak (P): P trains run during peak travel times. They provide additional alternatives when you’re travelling during busy periods. Most of these trains run in the mornings and in late afternoon.
- Local trains (L): L trains generally connect cities, but they also stop at every station along the route.
- S-trains (S): S trains are suburban trains that connect the city centre with the surrounding communes. S trains stop in most stations along the route.
- EuroCity (EC): EC trains connect Europe’s major cities, stopping at key stations, offering comfort, dining, and scenic international routes.

EXTRA: Additional train services, used at exceptionally busy periods. For example, these are the trains that travel towards the Belgian coast on very sunny days.
- T (Touristic): Additional train service to certain tourist destinations.
- EXP (Coast Express): Extra train service to the Belgian coast during the summer period.
- International trains (INT = EC, THA, TGV, ICE, EST): Regular international trains, namely Eurocity, Thalys, TGV, ICE and Eurostar.

In [7]:
import pandas as pd
file_path = DATA_DIR / 'ireland/routes.txt'
routes = pd.read_csv(file_path, sep=',', header=0)
routes.head()

,route_id,agency_id,route_short_name,route_long_name,route_desc,route_type,route_url,route_color,route_text_color,route_sort_order,continuous_pickup,continuous_drop_off
0,3-3001_36302,3-7778068,290a,"Tralee, Tesco, The Square - Tralee, Tesco, The...",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
1,3-3001_36303,3-7778068,290b,"Tralee, Tesco, The Square - Tralee, Tesco, The...",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
2,3-3026_40268,3-7778268,Dk01,"Dunshaughlin (Euromart Shop) - Dundalk, Dkit D...",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
3,3-3026_40269,3-7778268,Dk02,"Moynalty, Moynalty - Dundalk, Dkit Dublin Road",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
4,3-3026_40270,3-7778268,Dk03,"Market Square Navan - Dundalk, Dkit Dublin Road",NaN,3,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
temp_df1, temp_df2 = process_route_data(L_graph, routes, 27, 235)

Data for nodes (27, 235):
Average Duration: 360.0
Number of Vehicles: 3
Headsign: {'Ottignies': 2, 'Louvain-la-Neuve': 1}

Data for nodes (235, 27):
Average Duration: 420.0
Number of Vehicles: 3
Headsign: {'Schaerbeek': 3}

Result for nodes (27, 235):

Empty DataFrame
Columns: []
Index: []

Result for nodes (235, 27):

Empty DataFrame
Columns: []
Index: []

### Sanity check
This function prints some useful information that might help further cleaning the graph

In [7]:
sanity_check(L_graph)

Checking self loops...
---
Checking links only on one direction...
Edge exists only in one direction:  Ballybrophy  (node 14)  to Templemore Station  (node 13)
Edge exists only in one direction:  Sydney Parade  (node 79)  to Lansdowne Road  (node 68)
---
Checking edges with invalid duration...
---
Number of edges:  314
Number of nodes:  150
Number of strongly connected components: 1

## Check Nodes

### Find Node

In [5]:
plot_nodes_highlight(L_graph, [27,235])

BokehDeprecationWarning: 'get_provider' was deprecated in Bokeh 3.0.0 and will be removed, use 'add_tile directly' instead.

### Degree of Node Check
This function lists out the degree (incoming and outgoing edges) of each node in descending order

In [7]:
node_degrees_table(L_graph).head(10)

,Node Number,Node Name,Total (In+Out),Ingoing,Outgoing
5,5,Dublin Connolly,10,5,5
82,82,Howth Junction and Donaghmede,8,4,4
9,9,Limerick Junction,8,4,4
66,66,Dun Laoghaire (Mallin),8,4,4
91,91,Manulla Junction,6,3,3
15,15,Portarlington,6,3,3
111,111,Drumcondra,6,3,3
114,114,Clonsilla,6,3,3
54,54,Park West and Cherry Orchard,6,3,3
128,128,Glounthaune,6,3,3

In [8]:
node_degrees_table(L_graph)[node_degrees_table(L_graph)["Total (In+Out)"] % 2 == 1]  # Select rows where the value is odd

    Node Number           Node Name  Total (In+Out)  Ingoing  Outgoing
79           79       Sydney Parade               5        2         3
14           14         Ballybrophy               5        2         3
68           68      Lansdowne Road               5        3         2
13           13  Templemore Station               3        2         1

### Train Frequency of Node

In [9]:
stations_trains_df(L_graph).head(10)

   Node Number                      Node Name  Degree  Num Trains
0            5                Dublin Connolly      10         470
1           71                    Tara Street       4         436
2           70                  Dublin Pearse       6         433
3           82  Howth Junction and Donaghmede       8         376
4           69               Grand Canal Dock       4         374
5           66         Dun Laoghaire (Mallin)       8         339
6           68                 Lansdowne Road       5         324
7          142                       Seapoint       4         324
8          143         Salthill and Monkstown       4         324
9           79                  Sydney Parade       5         322